### ISSUE TITLE
Rendering stops when error thrown from node callback

### ISSUE THREAD

**Issue by kevinsawicki** [photoionization/cefode#6]
The render thread seems to die if you throw an error from a node callback.

``` javascript
require('fs').stat('/', function() {throw new Error()})
```

Running the above code from the dev tools causes the entire window to stop rendering.

**Comment by zcbenz** [comment]
Welcome to one of the dark corners of cefode!

Usually when you throw exceptions in the callback of node's native module, you are under node's context, and WebKit will crash because it wants to find the troubling window from current context, which however doesn't belong to any window.

So I did a hack here when current context is node context, WebKit will switch to the creation context of the exception, so everything will work fine.

But if you throw a value instead of a object, WebKit will fail to print it to devtools's console because it cannot find from which window the exception comes.
